apiVersion: apps/v1
kind: Deployment

# Deployment basic info
metadata:
  name: spring-deployment # Deployment name

# Deployment detail info
spec:
  replicas: 3 # Number of pod replicas to create
  selector:
    matchLabels:
      app: backend-app

  # 배포할 Pod 정의
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: spring-container
          image: spring-server # image name & version
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MY_ACCOUNT
              value: jude bellingham
            - name: MY_PASSWORD
              value: pwd_realmadrid